<a href="https://colab.research.google.com/github/anas1IA/Analysis-of-Bank-Debit-Collections/blob/main/Data/scarpe_from_youtube.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
my_api = "AIzaSyC3mSypuaR1Cc6m366BS8e5D5UWWTldt9Y"

In [ ]:
#!pip install google-api-python-client

In [ ]:
from googleapiclient.discovery import build
import numpy as np
import pandas as pd

In [ ]:
api_service_name = "youtube"
api_version = "v3"
DEVELOPER_KEY = my_api

youtube = build(api_service_name, api_version, developerKey=DEVELOPER_KEY)

In [ ]:
cols = ["videoId", "authorChannelId", "authorDisplayName", "textDisplay",
          "textOriginal", "publishedAt", "updatedAt","likeCount", "canReply" ,"totalReplyCount"]

In [ ]:
def comment(item):
  item1 = item["snippet"]

  snippet = item1["topLevelComment"]["snippet"]

  for col in cols:
    try:
      if col in ("canReply","totalReplyCount"):
        data_dict[col].append(item1[col])
      else:
        s = snippet[col]
        if s != None and s != 'none':
          if col == "authorChannelId":
            data_dict[col].append(s["value"])
          else:
            data_dict[col].append(s)

        else:
          data_dict[col].append(np.nan)
    except Exception as e:
      data_dict[col].append(np.nan)
      raise e

  return data_dict

In [ ]:
video_id = "17bzlWIGH3g"

In [ ]:
data_dict = {col : [] for col in cols}

request = youtube.commentThreads().list(
        part="snippet",
        videoId=video_id,
        textFormat="plainText",
        maxResults=10000,
        order='time'
    )

response = request.execute()
while response:
    for item in response["items"]:
      data_dict = comment(item)
    if 'nextPageToken' in response:
        request = youtube.commentThreads().list(
            part="snippet",
            videoId=video_id,
            textFormat="plainText",
            maxResults=10000,
            order='time',
            pageToken=response['nextPageToken']
        )
        response = request.execute()
    else:
        break

In [ ]:
data = pd.DataFrame(data_dict)

In [ ]:
data

,videoId,authorChannelId,authorDisplayName,textDisplay,textOriginal,publishedAt,updatedAt,likeCount,canReply,totalReplyCount
0,17bzlWIGH3g,UCfQOzgNxhofa3tLytH7Il2A,Berti Ballermann,I loved Prof. Lennox's explanation of narrow A...,I loved Prof. Lennox's explanation of narrow A...,2023-04-07T15:59:58Z,2023-04-07T15:59:58Z,0,True,0
1,17bzlWIGH3g,UCjI_66LbnMitzvRBKjxJ52A,Mansour Bendago,Last segment is controversial as he is trying ...,Last segment is controversial as he is trying ...,2023-04-07T14:16:06Z,2023-04-07T14:16:06Z,0,True,0
2,17bzlWIGH3g,UCUi09HLDL3ffzdGSXEEkYyQ,SKYWalkers SG,"""trust the science"" is a most unscientific phrase","""trust the science"" is a most unscientific phrase",2023-04-07T13:13:40Z,2023-04-07T13:13:40Z,0,True,0
3,17bzlWIGH3g,UCXcbDED12gZgh4xhPeKnd0g,Mark Sandsmith,Next time interview an expert.,Next time interview an expert.,2023-04-07T10:32:24Z,2023-04-07T10:32:24Z,0,True,0
4,17bzlWIGH3g,UCO-QERAAgOuJeCarlI-1y0g,kaloncar,Thank you John Anderson and John Lennox. I c...,Thank you John Anderson and John Lennox. I c...,2023-04-07T09:52:52Z,2023-04-07T09:52:52Z,0,True,0
...,...,...,...,...,...,...,...,...,...,...
619,17bzlWIGH3g,UCgtNguQsXZhn1xrCW8xkesw,Marshall Bishop,Great conversation. These guys might want to r...,Great conversation. These guys might want to r...,2022-08-05T05:03:35Z,2022-08-05T05:03:35Z,3,True,3
620,17bzlWIGH3g,UC_B7zrshApEsBFL9p8dm1HQ,Matt Dugas,Family a fact or belief?,Family a fact or belief?,2022-08-05T04:33:10Z,2022-08-05T04:33:10Z,0,True,0
621,17bzlWIGH3g,UC_B7zrshApEsBFL9p8dm1HQ,Matt Dugas,"If Motherâ€™s Earth ðŸŒŽ, whoâ€™s your Daddy!?","If Motherâ€™s Earth ðŸŒŽ, whoâ€™s your Daddy!?",2022-08-05T04:29:16Z,2022-08-05T04:29:16Z,1,True,4
622,17bzlWIGH3g,UCfW9c0r5vMbXcO8T3mNV-ow,Bo Deutscher,This guy is a legend I canâ€™t wait to watch thi...,This guy is a legend I canâ€™t wait to watch thi...,2022-08-05T04:04:05Z,2022-08-05T04:04:05Z,33,True,1
623,17bzlWIGH3g,UCWbv7YKHBjggIZEQgwM2JQg,Donna T63,Best man on earth to interview. Love it!! Than...,Best man on earth to interview. Love it!! Than...,2022-08-05T04:02:35Z,2022-08-05T04:02:35Z,26,True,0